// demo/minesweeper/vue/board.vue
<script setup lang="ts">
import { computed, useTemplateRef } from 'vue'
import { useBoardEvent } from './use'
import Block from './block.vue'
import type { Operation, Cell } from '../model'
import type { Settings } from '../theme'

const props = defineProps<{
  settings: Settings
  cellGrid: Cell[][]
  operate: (cell: Cell, op: Operation) => void
  getAdjacentCells: (cell: Cell) => Cell[]
}>()

const column = computed(() => props.cellGrid[0].length)
const stride = computed(() => props.settings.size + props.settings.gap)

const boardRef = useTemplateRef('board')

const { enableHighlight, pointerPosition } = useBoardEvent(boardRef, op => {
  const cell = hoveredCell.value
  if (!cell) return

  const { flagMode, fastMode } = props.settings

  if (flagMode && op === 'reveal') {
    props.operate(cell, 'toggle-flag')
    return
  }

  if (fastMode && op === 'reveal' && cell.state === 'revealed') {
    props.operate(cell, 'chord-reveal')
    return
  }

  props.operate(cell, op)
})

const hoveredCell = computed(() => {
  const { x, y } = pointerPosition.value
  const { size } = props.settings

  const col = Math.floor(x / stride.value)
  const row = Math.floor(y / stride.value)
  const offsetX = x - col * stride.value
  const offsetY = y - row * stride.value

  return offsetX <= size && offsetY <= size
    ? props.cellGrid[row]?.[col]
    : undefined
})

const highlightedCells = computed(() => {
  if (!enableHighlight.value) return

  const cell = hoveredCell.value
  if (!cell || cell.state === 'flagged') return

  if (cell.state === 'covered') return [cell]

  return props.getAdjacentCells(cell).filter(c => c.state === 'covered')
})
</script>

<template>
  <div
    :style="{
      '--cell-size': `${props.settings.size}px`,
      '--gap': `${props.settings.gap}px`,
      '--cell-font-size': `${props.settings.size * 0.6}px`,
      '--cell-rounded': `${props.settings.rounded}px`,
      '--columns': column,
    }"
    class="w-fit max-w-full overflow-auto p-1 text-(length:--cell-font-size)"
  >
    <div
      ref="board"
      class="grid grid-cols-[repeat(var(--columns),1fr)] gap-(--gap)"
    >
      <template v-for="(row, rowIndex) in props.cellGrid" :key="rowIndex">
        <Block
          v-for="cell in row"
          :key="cell.index"
          :palette="props.settings.palette"
          :highlighted="highlightedCells?.includes(cell)"
          v-bind="cell"
        />
      </template>
    </div>
  </div>
</template>

// puzzles/minesweeper/react/Board.tsx
import { useMemo, useRef } from 'react'
import { cn } from '@/lib/utils'
import { cellAt } from '../utils'
import { useGameBoard } from './use'
import type { UserOptions } from '../options'
import type { Cell, Operation } from '../model'
import { emojis } from '../assets/config.json'

const GRADIENT =
  'bg-linear-to-br from-(--cell-from) to-(--cell-to) border-(--cell-border)'
const HI_GRADIENT =
  'bg-linear-to-br from-(--cell-hi-from) to-(--cell-hi-to) border-(--cell-border)'

export function BoardCell(props: Cell & { highlighted?: boolean }) {
  const { status, mine, adjacentMineCount, highlighted = false } = props

  const { txt, num } = useMemo(() => {
    if (status == 'exploded') {
      return { txt: emojis['boom'] }
    }
    if (status === 'flagged' || status === 'misflagged') {
      return { txt: emojis['flag'] }
    }
    if (status === 'revealed') {
      if (mine) return { txt: emojis['mine'] }

      const num = props.adjacentMineCount?.toString()
      return { txt: num, num }
    }
    return { txt: '' }
  }, [status, mine, adjacentMineCount])

  const cellStyle = useMemo(() => {
    if (status === 'exploded') {
      return 'animate-boom-shake border-transparent bg-red-600'
    }
    if (status === 'misflagged') {
      return 'border-transparent bg-red-300'
    }
    if (status === 'revealed' || highlighted) {
      return HI_GRADIENT
    }
    return `${GRADIENT} hover:from-(--c300) hover:to-(--c400)`
  }, [status, highlighted])

  return (
    <div
      data-num={num}
      className={cn(
        'flex size-(--cell-size) items-center justify-center rounded-(--cell-radius) border font-mono font-bold transition-[background-color]',
        cellStyle,
      )}
    >
      {txt}
    </div>
  )
}

export default function GameBoard(props: {
  isReady?: boolean
  options: UserOptions
  gridCells: Cell[][]
  getAdjacentCells: (i: number) => Cell[]
  onOperate: (i: number, op: Operation) => void
}) {
  const boardRef = useRef<HTMLDivElement>(null)

  const { radius, size, gap, palette, flagMode } = props.options
  const columns = props.gridCells[0]?.length ?? 0

  const cssVars = useMemo(
    () =>
      ({
        '--col': `${columns}`,
        '--gap': `${gap}px`,
        '--cell-fontsize': `${size * 0.61}px`,
        '--cell-radius': `${radius}px`,
        '--cell-size': `${size}px`,
      }) as Record<string, string>,
    [columns, radius, size, gap],
  )

  const { enableHighlight, pointerPosition } = useGameBoard(
    boardRef,
    (op, p) => {
      const grid = cellAt(p, size, gap)
      if (!grid) return

      const cell = props.gridCells[grid.y][grid.x]
      if (!cell) return

      let modifiedOp = op
      if (op === 'reveal') {
        if (cell.status === 'revealed') {
          modifiedOp = 'chord-reveal'
        } else if (flagMode && !props.isReady) {
          modifiedOp = 'toggle-flag'
        }
      }

      props.onOperate(cell.index, modifiedOp)
    },
  )

  const hoveredCell = useMemo(() => {
    if (!pointerPosition) return

    const grid = cellAt(pointerPosition, size, gap)
    if (!grid) return

    return props.gridCells[grid.y][grid.x]
  }, [pointerPosition, size, gap, props.gridCells])

  const hoveredCellRef = useRef(hoveredCell)
  hoveredCellRef.current = hoveredCell

  const highlightedIndices = useMemo(() => {
    if (!enableHighlight) return

    const cell = hoveredCellRef.current
    if (!cell) return

    if (cell.status === 'flagged' || (flagMode && cell.status === 'covered'))
      return

    if (cell.status === 'covered') {
      return [cell.index]
    }

    return props
      .getAdjacentCells(cell.index)
      .filter(c => c.status === 'covered')
      .map(c => c.index)
  }, [enableHighlight, hoveredCell, flagMode])

  return (
    <div
      style={cssVars}
      data-palette={palette}
      className="mx-auto w-fit max-w-full overflow-auto p-0.5 select-none"
    >
      <div
        ref={boardRef}
        className="grid grid-cols-[repeat(var(--col),1fr)] gap-(--gap) text-(length:--cell-fontsize)"
      >
        {props.gridCells.map(row => {
          return row.map(cell => (
            <BoardCell
              key={cell.index}
              {...cell}
              highlighted={highlightedIndices?.includes(cell.index)}
            />
          ))
        })}
      </div>
    </div>
  )
}
