// demo/minesweeper/vue/board.vue
<script setup lang="ts">
import { computed, useTemplateRef } from 'vue'
import { useBoardEvent } from './use'
import Block from './block.vue'
import type { Operation, Cell } from '../model'
import type { Settings } from '../theme'

const props = defineProps<{
  settings: Settings
  cellGrid: Cell[][]
  operate: (cell: Cell, op: Operation) => void
  getAdjacentCells: (cell: Cell) => Cell[]
}>()

const column = computed(() => props.cellGrid[0].length)
const stride = computed(() => props.settings.size + props.settings.gap)

const boardRef = useTemplateRef('board')

const { enableHighlight, pointerPosition } = useBoardEvent(boardRef, op => {
  const cell = hoveredCell.value
  if (!cell) return

  const { flagMode, fastMode } = props.settings

  if (flagMode && op === 'reveal') {
    props.operate(cell, 'toggle-flag')
    return
  }

  if (fastMode && op === 'reveal' && cell.state === 'revealed') {
    props.operate(cell, 'chord-reveal')
    return
  }

  props.operate(cell, op)
})

const hoveredCell = computed(() => {
  const { x, y } = pointerPosition.value
  const { size } = props.settings

  const col = Math.floor(x / stride.value)
  const row = Math.floor(y / stride.value)
  const offsetX = x - col * stride.value
  const offsetY = y - row * stride.value

  return offsetX <= size && offsetY <= size
    ? props.cellGrid[row]?.[col]
    : undefined
})

const highlightedCells = computed(() => {
  if (!enableHighlight.value) return

  const cell = hoveredCell.value
  if (!cell || cell.state === 'flagged') return

  if (cell.state === 'covered') return [cell]

  return props.getAdjacentCells(cell).filter(c => c.state === 'covered')
})
</script>

<template>
  <div
    :style="{
      '--cell-size': `${props.settings.size}px`,
      '--gap': `${props.settings.gap}px`,
      '--cell-font-size': `${props.settings.size * 0.6}px`,
      '--cell-rounded': `${props.settings.rounded}px`,
      '--columns': column,
    }"
    class="w-fit max-w-full overflow-auto p-1 text-(length:--cell-font-size)"
  >
    <div
      ref="board"
      class="grid grid-cols-[repeat(var(--columns),1fr)] gap-(--gap)"
    >
      <template v-for="(row, rowIndex) in props.cellGrid" :key="rowIndex">
        <Block
          v-for="cell in row"
          :key="cell.index"
          :palette="props.settings.palette"
          :highlighted="highlightedCells?.includes(cell)"
          v-bind="cell"
        />
      </template>
    </div>
  </div>
</template>

// demo/minesweeper/react/Board.tsx
import React, { useMemo, useRef } from 'react'
import { cn, type Position } from '@/lib/utils'
import { cellAt, themeLoader, type Settings } from '../utils'
import { useGameBoard } from './use'
import type { Cell, Operation } from '../model'

export type CellVariant = 'normal' | 'hi' | 'exploded' | 'misflagged'

export function BoardCell(props: { cell: Cell; highlighted?: boolean }) {
  const { cell, highlighted = false } = props
  const { type, mine, adjacentMineCount } = cell

  const { label, num } = useMemo(() => {
    if (type === 'exploded') {
      return { label: themeLoader.getEmoji('boom') }
    }
    if (type === 'flagged' || type === 'misflagged') {
      return { label: themeLoader.getEmoji('flag') }
    }
    if (type === 'revealed') {
      if (mine) return { label: themeLoader.getEmoji('mine') }

      const num = adjacentMineCount!.toString()
      return { label: num, num }
    }
    return { label: '' }
  }, [type, mine, adjacentMineCount])

  const variant: CellVariant = useMemo(() => {
    switch (type) {
      case 'covered':
      case 'flagged':
        return highlighted ? 'hi' : 'normal'
      case 'revealed':
        return 'hi'
      case 'exploded':
        return 'exploded'
      case 'misflagged':
        return 'misflagged'
    }
  }, [type, highlighted])

  return (
    <div
      data-num={num}
      data-variant={variant}
      className={cn(
        'flex size-(--cell-size) items-center justify-center rounded-(--cell-radius) border font-mono font-bold transition-[background-color]',
        variant !== 'exploded' && variant !== 'misflagged'
          ? 'border-(--cell-border) bg-linear-to-br from-(--cell-from) to-(--cell-to)'
          : '',
        variant === 'exploded' &&
          'animate-boom-shake border-transparent bg-red-600',
        variant === 'misflagged' && 'border-transparent bg-red-300',
      )}
    >
      {label}
    </div>
  )
}

export default function GameBoard(props: {
  settings: Settings
  gridCells: Cell[][]
  onOperate: (i: number, op: Operation) => void
  getAdjacentCells: (i: number) => Cell[]
}) {
  const boardRef = useRef<HTMLDivElement>(null)

  const columns = props.gridCells[0]?.length ?? 0
  const { size, gap, radius } = props.settings

  const cssVars = useMemo(
    () =>
      ({
        '--col': `${columns}`,
        '--gap': `${gap}px`,
        '--cell-fontsize': `${size * 0.65}px`,
        '--cell-radius': `${radius}px`,
        '--cell-size': `${size}px`,
      }) as React.CSSProperties,
    [columns, gap, radius, size],
  )

  const { enableHighlight, pointerPosition } = useGameBoard(
    boardRef,
    (op: Operation, pos: Position) => {
      const grid = cellAt(pos, size, gap)
      if (!grid) return

      const cell = props.gridCells[grid.y][grid.x]
      if (!cell) return

      const { fastMode, flagMode } = props.settings
      if (fastMode && op === 'reveal' && cell.type === 'revealed') {
        props.onOperate(cell.index, 'chord-reveal')
        return
      }
      if (flagMode && op === 'reveal') {
        props.onOperate(cell.index, 'toggle-flag')
        return
      }
      props.onOperate(cell.index, op)
    },
  )

  const hoveredCell = useMemo(() => {
    if (!pointerPosition) return

    const grid = cellAt(pointerPosition, size, gap)
    if (!grid) return

    return props.gridCells[grid.y][grid.x]
  }, [pointerPosition, size, gap, props.gridCells])

  const hoveredCellRef = useRef(hoveredCell)
  hoveredCellRef.current = hoveredCell

  const highlightedIndices = useMemo(() => {
    if (!enableHighlight) return

    const cell = hoveredCellRef.current
    if (!cell || cell.type === 'flagged') return

    if (cell.type === 'covered') {
      return [cell.index]
    }

    return props
      .getAdjacentCells(cell.index)
      .filter(c => c.type === 'covered')
      .map(c => c.index)
  }, [enableHighlight, props.getAdjacentCells, hoveredCell])

  return (
    <div
      style={cssVars}
      className="mx-auto w-fit max-w-full overflow-auto p-0.5 select-none"
    >
      <div
        ref={boardRef}
        data-palette={props.settings.palette}
        className="grid grid-cols-[repeat(var(--col),1fr)] gap-(--gap) text-(length:--cell-fontsize)"
      >
        {props.gridCells.map(row => {
          return row.map(cell => (
            <BoardCell
              key={cell.index}
              cell={cell}
              highlighted={highlightedIndices?.includes(cell.index)}
            />
          ))
        })}
      </div>
    </div>
  )
}
